import PoincareCurvature.Geometry.Manifold.RicciFlow.StandardRicciDeTurckCoordinateOperator

#print axioms RicciFlow.contMDiffOn_actualBackgroundFrameDerivative
#print axioms RicciFlow.contMDiffOn_actualBackgroundFrameCoeff
#print axioms RicciFlow.contDiffOn_scalarReadout_actualBackgroundFrameCoeff
#print axioms RicciFlow.contDiffOn_actualBackgroundCoordinates
#print axioms RicciFlow.actualBackgroundCoordinates_eq_frameCoeff
#print axioms RicciFlow.backgroundFirst_actualBackgroundCoordinates_eq_mvfderiv
#print axioms RicciFlow.chosenLC_coordinateFrame_metricCompatibility
#print axioms RicciFlow.standardDeTurck_coordinateFrameCoeff_eq_deTurck
#print axioms RicciFlow.standardDeTurckCoordinates_eq_deTurck
#print axioms RicciFlow.standardDeTurckCoordinates_eventuallyEq_deTurck
#print axioms RicciFlow.differentiableAt_standardDeTurckCoordinates
#print axioms RicciFlow.fderiv_standardDeTurckCoordinates_apply
#print axioms RicciFlow.contMDiffOn_standardDeTurckFrameCoeff
#print axioms RicciFlow.contDiffOn_scalarReadout_standardDeTurckFrameCoeff
#print axioms RicciFlow.standardDeTurck_coordinateFrameCoeff_mvfderiv_eq_deTurckFirst
#print axioms RicciFlow.standardDeTurck_coordinateFrameCoeff_covariantDerivative_eq
#print axioms RicciFlow.standardDeTurckCorrection_coordinateFrame_eq_coordinateLie
#print axioms RicciFlow.standardRicciDeTurckRHS_coordinateFrame_eq_coordinateRD
#print axioms RicciFlow.standardRicciDeTurckRHS_coordinateFrame_eq_correctedJet
#print axioms RicciFlow.standardRicciDeTurckRHS_coordinateFrame_eq_principal_add_lowerOrder
#print axioms RicciFlow.standardRicciDeTurckRHS_coordinateFrame_eq_frozenPrincipal_add_remainder
