import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.CoordinateJetConnectionDerivative

#print axioms PoincareCurvature.hasDerivAt_nonsing_inv_entry_of_det_ne_zero
#print axioms PoincareCurvature.CoordinateMatrixJet.hasDerivAt_coordinateLine
#print axioms PoincareCurvature.CoordinateMatrixJet.hasDerivAt_comp_coordinateLine
#print axioms PoincareCurvature.CoordinateMatrixJet.differentiableAt_inverse_entry
#print axioms PoincareCurvature.CoordinateMatrixJet.fderiv_inverse_apply
#print axioms PoincareCurvature.CoordinateMatrixJet.inverseFirst_eq_sum
#print axioms PoincareCurvature.CoordinateMatrixJet.differentiableAt_christoffel
#print axioms PoincareCurvature.CoordinateMatrixJet.fderiv_christoffel_apply
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.invMetricOfJet_coordinateJet_eq_inverse
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.derivInvMetricOfJet_coordinateJet_eq_inverseFirst
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.fderiv_invMetricOfJet_coordinateJet_apply
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.christoffelOfJet_coordinateJet_eq_christoffel
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.derivChristoffelOfJet_coordinateJet_eq_christoffelFirst
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.fderiv_christoffelOfJet_coordinateJet_apply
