import PoincareCurvature.Geometry.Manifold.RicciFlow.MetricContractedDeTurckField

#print axioms PoincareCurvature.metricBilinearContraction_eq_sum_inverseGram
#print axioms PoincareCurvature.metricContractSymbol_ne_ordinaryTraceRaisedSymbol_conformal_two
#print axioms CovariantDerivative.metricConnectionDifferenceVector_localFrameCoeff
#print axioms CovariantDerivative.metricConnectionDifferenceVector_eq_zero_of_isLeviCivita
#print axioms RicciFlow.metricContractedDeTurckVectorField_eq_zero_of_isLeviCivita
