import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedTimeKernel
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedHessianTimeEnvelope
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedDuhamelIntegrand
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedDuhamelHessianIntegral
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedDuhamelHessianDerivative
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedDuhamelFrechet
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedDuhamelHessianTrace
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.WeightedDuhamelHessianFrechetTrace
import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.EuclideanHeatRegularizerC2Trace

set_option pp.universes false
set_option format.width 240

open Real Set MeasureTheory
open scoped Real BigOperators Interval Topology

#print axioms RicciFlow.AnalyticPDE.weightedTimeKernel
#print axioms RicciFlow.AnalyticPDE.weightedTimeKernel_integrable_and_integral_le
#print axioms RicciFlow.AnalyticPDE.intervalIntegrable_weightedTimeKernel
#print axioms RicciFlow.AnalyticPDE.integral_weightedTimeKernel_le
#print axioms RicciFlow.AnalyticPDE.weightedHessianTimeEnvelope
#print axioms RicciFlow.AnalyticPDE.weightedHessianTimeEnvelope_eq_weightedTimeKernel
#print axioms RicciFlow.AnalyticPDE.intervalIntegrable_weightedHessianTimeEnvelope
#print axioms RicciFlow.AnalyticPDE.integral_weightedHessianTimeEnvelope_le
#print axioms RicciFlow.AnalyticPDE.abs_heatHessianEntryConvolutionND_le_weighted_envelope
#print axioms RicciFlow.AnalyticPDE.ae_norm_heatHessianEntryConvolution_le_weighted_envelope
#print axioms RicciFlow.AnalyticPDE.intervalIntegrable_heatHessianEntryConvolution_of_weighted
#print axioms RicciFlow.AnalyticPDE.abs_heatDuhamelHessianEntryND_le_weighted
#print axioms RicciFlow.AnalyticPDE.continuous_heatDuhamelHessianEntryND_of_weighted
#print axioms RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianEntryNDbcf
#print axioms RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianEntryNDbcf_apply
#print axioms RicciFlow.AnalyticPDE.hasDerivAt_heatDuhamelGradientCoordND_entry_of_weighted
#print axioms RicciFlow.AnalyticPDE.hasDerivAt_partial_heatDuhamelND_coord_entry_of_weighted
#print axioms RicciFlow.AnalyticPDE.deriv_partial_heatDuhamelND_coord_entry_eq_of_weighted
#print axioms RicciFlow.AnalyticPDE.coordinateHessianCLM_single_left
#print axioms RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianCLM
#print axioms RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianCLM_apply
#print axioms RicciFlow.AnalyticPDE.continuous_weightedHeatDuhamelHessianCLM
#print axioms RicciFlow.AnalyticPDE.hasFDerivAt_heatDuhamelGradientCoordND_of_weighted
#print axioms RicciFlow.AnalyticPDE.continuous_heatDuhamelGradientCLM_of_weighted
#print axioms RicciFlow.AnalyticPDE.hasFDerivAt_heatDuhamelND_of_weighted
#print axioms RicciFlow.AnalyticPDE.hasFDerivAt_heatDuhamelGradientCLM_of_weighted
#print axioms RicciFlow.AnalyticPDE.hasFDerivAt_fderiv_heatDuhamelND_of_weighted
#print axioms RicciFlow.AnalyticPDE.fderiv_fderiv_heatDuhamelND_eq_of_weighted
#print axioms RicciFlow.AnalyticPDE.contDiff_two_heatDuhamelND_of_weighted
#print axioms RicciFlow.AnalyticPDE.norm_weightedHeatDuhamelHessianCLM_le
#print axioms RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianCLM_comm
#print axioms RicciFlow.AnalyticPDE.HasWeightedSpatialHolderOn
#print axioms RicciFlow.AnalyticPDE.LittleWeightedSpatialHolder
#print axioms RicciFlow.AnalyticPDE.weightedHessianEntryTraceConstant
#print axioms RicciFlow.AnalyticPDE.weightedHessianEntryTraceConstant_nonneg
#print axioms RicciFlow.AnalyticPDE.HasWeightedSpatialHolderOn.mono_right
#print axioms RicciFlow.AnalyticPDE.abs_heatDuhamelHessianEntryND_le_on_initial_interval
#print axioms RicciFlow.AnalyticPDE.exists_initial_interval_heatDuhamelHessianEntryND_le_of_little
#print axioms RicciFlow.AnalyticPDE.exists_initial_interval_heatDuhamelHessianEntryND_lt_of_little
#print axioms RicciFlow.AnalyticPDE.littleWeightedHeatDuhamelHessianEntryNDbcf
#print axioms RicciFlow.AnalyticPDE.littleWeightedHeatDuhamelHessianEntryNDbcf_apply
#print axioms RicciFlow.AnalyticPDE.littleWeightedHeatDuhamelHessianEntryNDbcf_initial
#print axioms RicciFlow.AnalyticPDE.norm_littleWeightedHeatDuhamelHessianEntryNDbcf_le
#print axioms RicciFlow.AnalyticPDE.exists_initial_interval_littleWeightedHessian_norm_lt
#print axioms RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntryNDbcf_zero
#print axioms RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntries_zero
#print axioms RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntries_norm_zero
#print axioms RicciFlow.AnalyticPDE.weightedHessianOperatorTraceConstant
#print axioms RicciFlow.AnalyticPDE.weightedHessianOperatorTraceConstant_nonneg
#print axioms RicciFlow.AnalyticPDE.norm_weightedHeatDuhamelHessianCLM_le_trace_constant
#print axioms RicciFlow.AnalyticPDE.exists_initial_interval_fderiv_fderiv_heatDuhamelND_norm_lt_of_little
#print axioms RicciFlow.AnalyticPDE.heatHessianMajorantND
#print axioms RicciFlow.AnalyticPDE.heatHessianMajorantND_nonneg
#print axioms RicciFlow.AnalyticPDE.integrable_heatHessianMajorantND
#print axioms RicciFlow.AnalyticPDE.integral_heatHessianMajorantND
#print axioms RicciFlow.AnalyticPDE.abs_heatHessianKernelEntryND_le_majorantPair
#print axioms RicciFlow.AnalyticPDE.heatHessianMajorantFirstMoment
#print axioms RicciFlow.AnalyticPDE.heatHessianMajorantPairFirstMoment
#print axioms RicciFlow.AnalyticPDE.integrable_abs_coord_mul_heatHessianMajorantND
#print axioms RicciFlow.AnalyticPDE.time_mul_integral_abs_coord_heatHessianMajorantND
#print axioms RicciFlow.AnalyticPDE.abs_boundedContinuous_sub_le_affine_modulus
#print axioms RicciFlow.AnalyticPDE.abs_time_mul_heatHessianEntryConvolutionND_le_modulus
#print axioms RicciFlow.AnalyticPDE.abs_time_mul_heatHessianEntryConvolutionND_le
#print axioms RicciFlow.AnalyticPDE.timeMulHeatHessianEntryNDbcf
#print axioms RicciFlow.AnalyticPDE.timeMulHeatHessianEntryNDbcf_apply
#print axioms RicciFlow.AnalyticPDE.timeMulHeatHessianEntryPathBcf
#print axioms RicciFlow.AnalyticPDE.timeMulHeatHessianEntryPathBcf_apply_of_pos
#print axioms RicciFlow.AnalyticPDE.tendstoUniformly_time_mul_heatHessianEntryConvolutionND_zero
#print axioms RicciFlow.AnalyticPDE.tendsto_timeMulHeatHessianEntryPathBcf_zero
#print axioms RicciFlow.AnalyticPDE.tendstoUniformly_time_mul_heatSemigroupND_zero
#print axioms RicciFlow.AnalyticPDE.tendstoUniformly_time_mul_heatSemigroupGradientCoordND_zero
#print axioms RicciFlow.AnalyticPDE.heatRegularizer_C0_C1_C2_uniform_zero
#print axioms RicciFlow.AnalyticPDE.hasDerivAt_time_mul_heatSemigroupND_coord
#print axioms RicciFlow.AnalyticPDE.hasDerivAt_time_mul_heatSemigroupGradientCoordND_entry

#eval IO.println "WEIGHTED_HESSIAN_TYPES_BEGIN"
#check @RicciFlow.AnalyticPDE.weightedTimeKernel
#check @RicciFlow.AnalyticPDE.weightedTimeKernel_integrable_and_integral_le
#check @RicciFlow.AnalyticPDE.intervalIntegrable_weightedTimeKernel
#check @RicciFlow.AnalyticPDE.integral_weightedTimeKernel_le
#check @RicciFlow.AnalyticPDE.weightedHessianTimeEnvelope
#check @RicciFlow.AnalyticPDE.weightedHessianTimeEnvelope_eq_weightedTimeKernel
#check @RicciFlow.AnalyticPDE.intervalIntegrable_weightedHessianTimeEnvelope
#check @RicciFlow.AnalyticPDE.integral_weightedHessianTimeEnvelope_le
#check @RicciFlow.AnalyticPDE.abs_heatHessianEntryConvolutionND_le_weighted_envelope
#check @RicciFlow.AnalyticPDE.ae_norm_heatHessianEntryConvolution_le_weighted_envelope
#check @RicciFlow.AnalyticPDE.intervalIntegrable_heatHessianEntryConvolution_of_weighted
#check @RicciFlow.AnalyticPDE.abs_heatDuhamelHessianEntryND_le_weighted
#check @RicciFlow.AnalyticPDE.continuous_heatDuhamelHessianEntryND_of_weighted
#check @RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianEntryNDbcf
#check @RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianEntryNDbcf_apply
#check @RicciFlow.AnalyticPDE.hasDerivAt_heatDuhamelGradientCoordND_entry_of_weighted
#check @RicciFlow.AnalyticPDE.hasDerivAt_partial_heatDuhamelND_coord_entry_of_weighted
#check @RicciFlow.AnalyticPDE.deriv_partial_heatDuhamelND_coord_entry_eq_of_weighted
#check @RicciFlow.AnalyticPDE.coordinateHessianCLM_single_left
#check @RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianCLM
#check @RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianCLM_apply
#check @RicciFlow.AnalyticPDE.continuous_weightedHeatDuhamelHessianCLM
#check @RicciFlow.AnalyticPDE.hasFDerivAt_heatDuhamelGradientCoordND_of_weighted
#check @RicciFlow.AnalyticPDE.continuous_heatDuhamelGradientCLM_of_weighted
#check @RicciFlow.AnalyticPDE.hasFDerivAt_heatDuhamelND_of_weighted
#check @RicciFlow.AnalyticPDE.hasFDerivAt_heatDuhamelGradientCLM_of_weighted
#check @RicciFlow.AnalyticPDE.hasFDerivAt_fderiv_heatDuhamelND_of_weighted
#check @RicciFlow.AnalyticPDE.fderiv_fderiv_heatDuhamelND_eq_of_weighted
#check @RicciFlow.AnalyticPDE.contDiff_two_heatDuhamelND_of_weighted
#check @RicciFlow.AnalyticPDE.norm_weightedHeatDuhamelHessianCLM_le
#check @RicciFlow.AnalyticPDE.weightedHeatDuhamelHessianCLM_comm
#check @RicciFlow.AnalyticPDE.HasWeightedSpatialHolderOn
#check @RicciFlow.AnalyticPDE.LittleWeightedSpatialHolder
#check @RicciFlow.AnalyticPDE.weightedHessianEntryTraceConstant
#check @RicciFlow.AnalyticPDE.weightedHessianEntryTraceConstant_nonneg
#check @RicciFlow.AnalyticPDE.HasWeightedSpatialHolderOn.mono_right
#check @RicciFlow.AnalyticPDE.abs_heatDuhamelHessianEntryND_le_on_initial_interval
#check @RicciFlow.AnalyticPDE.exists_initial_interval_heatDuhamelHessianEntryND_le_of_little
#check @RicciFlow.AnalyticPDE.exists_initial_interval_heatDuhamelHessianEntryND_lt_of_little
#check @RicciFlow.AnalyticPDE.littleWeightedHeatDuhamelHessianEntryNDbcf
#check @RicciFlow.AnalyticPDE.littleWeightedHeatDuhamelHessianEntryNDbcf_apply
#check @RicciFlow.AnalyticPDE.littleWeightedHeatDuhamelHessianEntryNDbcf_initial
#check @RicciFlow.AnalyticPDE.norm_littleWeightedHeatDuhamelHessianEntryNDbcf_le
#check @RicciFlow.AnalyticPDE.exists_initial_interval_littleWeightedHessian_norm_lt
#check @RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntryNDbcf_zero
#check @RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntries_zero
#check @RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntries_norm_zero
#check @RicciFlow.AnalyticPDE.weightedHessianOperatorTraceConstant
#check @RicciFlow.AnalyticPDE.weightedHessianOperatorTraceConstant_nonneg
#check @RicciFlow.AnalyticPDE.norm_weightedHeatDuhamelHessianCLM_le_trace_constant
#check @RicciFlow.AnalyticPDE.exists_initial_interval_fderiv_fderiv_heatDuhamelND_norm_lt_of_little
#check @RicciFlow.AnalyticPDE.heatHessianMajorantND
#check @RicciFlow.AnalyticPDE.heatHessianMajorantND_nonneg
#check @RicciFlow.AnalyticPDE.integrable_heatHessianMajorantND
#check @RicciFlow.AnalyticPDE.integral_heatHessianMajorantND
#check @RicciFlow.AnalyticPDE.abs_heatHessianKernelEntryND_le_majorantPair
#check @RicciFlow.AnalyticPDE.heatHessianMajorantFirstMoment
#check @RicciFlow.AnalyticPDE.heatHessianMajorantPairFirstMoment
#check @RicciFlow.AnalyticPDE.integrable_abs_coord_mul_heatHessianMajorantND
#check @RicciFlow.AnalyticPDE.time_mul_integral_abs_coord_heatHessianMajorantND
#check @RicciFlow.AnalyticPDE.abs_boundedContinuous_sub_le_affine_modulus
#check @RicciFlow.AnalyticPDE.abs_time_mul_heatHessianEntryConvolutionND_le_modulus
#check @RicciFlow.AnalyticPDE.abs_time_mul_heatHessianEntryConvolutionND_le
#check @RicciFlow.AnalyticPDE.timeMulHeatHessianEntryNDbcf
#check @RicciFlow.AnalyticPDE.timeMulHeatHessianEntryNDbcf_apply
#check @RicciFlow.AnalyticPDE.timeMulHeatHessianEntryPathBcf
#check @RicciFlow.AnalyticPDE.timeMulHeatHessianEntryPathBcf_apply_of_pos
#check @RicciFlow.AnalyticPDE.tendstoUniformly_time_mul_heatHessianEntryConvolutionND_zero
#check @RicciFlow.AnalyticPDE.tendsto_timeMulHeatHessianEntryPathBcf_zero
#check @RicciFlow.AnalyticPDE.tendstoUniformly_time_mul_heatSemigroupND_zero
#check @RicciFlow.AnalyticPDE.tendstoUniformly_time_mul_heatSemigroupGradientCoordND_zero
#check @RicciFlow.AnalyticPDE.heatRegularizer_C0_C1_C2_uniform_zero
#check @RicciFlow.AnalyticPDE.hasDerivAt_time_mul_heatSemigroupND_coord
#check @RicciFlow.AnalyticPDE.hasDerivAt_time_mul_heatSemigroupGradientCoordND_entry
#print RicciFlow.AnalyticPDE.HasWeightedSpatialHolderOn
#print RicciFlow.AnalyticPDE.LittleWeightedSpatialHolder
#print RicciFlow.AnalyticPDE.weightedHessianEntryTraceConstant
#print RicciFlow.AnalyticPDE.weightedHessianOperatorTraceConstant
#eval IO.println "WEIGHTED_HESSIAN_TYPES_END"

#eval IO.println "WEIGHTED_HESSIAN_RANK_ZERO_BEGIN"
#check @RicciFlow.AnalyticPDE.abs_heatDuhamelHessianEntryND_le_weighted 0
#check @RicciFlow.AnalyticPDE.contDiff_two_heatDuhamelND_of_weighted 0
#check @RicciFlow.AnalyticPDE.fderiv_fderiv_heatDuhamelND_eq_of_weighted 0
#check @RicciFlow.AnalyticPDE.tendsto_littleWeightedHeatDuhamelHessianEntries_zero 0
#check @RicciFlow.AnalyticPDE.exists_initial_interval_fderiv_fderiv_heatDuhamelND_norm_lt_of_little 0
#check @RicciFlow.AnalyticPDE.heatRegularizer_C0_C1_C2_uniform_zero 0
#check @RicciFlow.AnalyticPDE.tendsto_timeMulHeatHessianEntryPathBcf_zero 0
#check @RicciFlow.AnalyticPDE.hasDerivAt_time_mul_heatSemigroupND_coord 0
example (j : Fin 0) : False := Fin.elim0 j
#eval IO.println "WEIGHTED_HESSIAN_RANK_ZERO_END"
