import PoincareCurvature.Geometry.Manifold.RicciFlow.ChosenLeviCivitaCoordinateChristoffel

#print axioms PoincareCurvature.PreferredCoordinateFrame.frame_eq_inverseChart_derivative
#print axioms PoincareCurvature.PreferredCoordinateFrame.mpullback_frame_eq_const
#print axioms PoincareCurvature.PreferredCoordinateFrame.mvfderiv_frame_eq_fderiv
#print axioms PoincareCurvature.PreferredCoordinateFrame.mlieBracket_frame_eq_zero
#print axioms PoincareCurvature.PreferredCoordinateFrame.toModel_coordinateVector
#print axioms PoincareCurvature.PreferredCoordinateFrame.fderiv_comp_toModel_coordinateVector
#print axioms CovariantDerivative.koszul_formula_at
#print axioms RicciFlow.isOpen_chosenLCCoordinateDomain
#print axioms RicciFlow.chosenLCMetricCoordinates_symm
#print axioms RicciFlow.contDiffOn_chosenLCMetricCoordinates
#print axioms RicciFlow.chosenLCMetricCoordinates_det_ne_zero_on_domain
#print axioms RicciFlow.first_chosenLCMetricCoordinates_eq_mvfderiv
#print axioms RicciFlow.chosenLC_inner_coordinateFrame_eq_first_metric
#print axioms RicciFlow.chosenLC_coordinateFrameCoeff_eq_christoffel
#print axioms RicciFlow.chosenLCConnectionCoordinates_eq_christoffel
#print axioms RicciFlow.chosenLCConnectionCoordinates_eventuallyEq_christoffel
#print axioms RicciFlow.differentiableAt_chosenLCConnectionCoordinates
#print axioms RicciFlow.fderiv_chosenLCConnectionCoordinates_apply
