import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.GenuineRicciDeTurckHeatInvariantClosure

#print axioms RicciFlow.AnalyticPDE.littleHolderPropagator_constLittleHolder
#print axioms RicciFlow.AnalyticPDE.jet2SectionLittleHolderPropagator_euclideanSection
#print axioms RicciFlow.AnalyticPDE.jet2SectionLittleHolderPropagator_mem_euclidean_closedBall
#print axioms RicciFlow.AnalyticPDE.jet2OfSection_heat_mem_phiRDNemytskiiData
#print axioms RicciFlow.AnalyticPDE.isGoodHolder_geometricNRDHolder_of_euclidean_closedBall
#print axioms RicciFlow.AnalyticPDE.geometricNRDLittleHolderOnEuclideanClosedBall_apply
#print axioms RicciFlow.AnalyticPDE.lipschitzOnWith_geometricNRDLittleHolderOnEuclideanClosedBall
