import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.CoordinateJetPrincipalRemainder

#print axioms PoincareCurvature.CoordinateMatrixJet.component_contDiffAt
#print axioms PoincareCurvature.CoordinateMatrixJet.component_hasFDerivAt
#print axioms PoincareCurvature.CoordinateMatrixJet.first_eq_matrix_fderiv
#print axioms PoincareCurvature.CoordinateMatrixJet.component_differential_hasFDerivAt
#print axioms PoincareCurvature.CoordinateMatrixJet.first_component_hasFDerivAt
#print axioms PoincareCurvature.CoordinateMatrixJet.fderiv_first_apply
#print axioms PoincareCurvature.CoordinateMatrixJet.second_derivative_symm
#print axioms PoincareCurvature.CoordinateMatrixJet.first_tensor_symm
#print axioms PoincareCurvature.CoordinateMatrixJet.second_tensor_symm
#print axioms RicciFlow.AnalyticPDE.coordinateJet_deriv2_derivative_symm
#print axioms RicciFlow.AnalyticPDE.coordinateJet_deriv2_tensor_symm
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRD_coordinateJet_eq_principal_add_lowerOrder
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDWithBackgroundJet_coordinateJet_eq_principal_add_lowerOrder
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDWithBackgroundJet_coordinateJet_eq_frozenPrincipal_add_remainder
