import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.RicciDeTurckPrincipalRemainder

#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.secondJetLinearReaction_eq_principal
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDOfJet_eq_principal_add_lowerOrder
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.lowerOrderRDOfJet_eq_of_val_deriv1
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDWithBackgroundJetOfJet_eq_sub_backgroundLieTerm
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.lowerOrderRDWithBackgroundJetOfJet_eq
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.lowerOrderRDWithBackgroundJetOfJet_eq_of_val_deriv1
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDWithBackgroundJetOfJet_eq_principal_add_lowerOrder
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDWithBackgroundJetOfJet_eq_frozenPrincipal_add_remainder
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.abs_frozenPrincipalError_le
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.phiRDWithBackgroundJetOfJet_zero
#print axioms RicciFlow.AnalyticPDE.GenuinePhiRD.hasDerivAt_conventionalContraction
