import PoincareCurvature.Geometry.Manifold.RicciFlow.GaugeReduction.MetricContractedDeTurckJointRegularity

#print axioms PoincareCurvature.metricBilinearContraction_eq_sum_inverseGram
#print axioms PoincareCurvature.metricContractSymbol_ne_ordinaryTraceRaisedSymbol_conformal_two
#print axioms CovariantDerivative.metricConnectionDifferenceVector_localFrameCoeff
#print axioms CovariantDerivative.metricConnectionDifferenceVector_eq_zero_of_isLeviCivita
#print axioms RicciFlow.metricContractedDeTurckVectorField_eq_zero_of_isLeviCivita

#print axioms RicciFlow.metricContractedDeTurckVectorField_eq_standardDeTurckVectorField
#print axioms PoincareCurvature.ParametrizedInner.contMDiffOn_timeDependentMetricContraction
#print axioms PoincareCurvature.ParametrizedInner.contMDiff_paramSection_neg
#print axioms RicciFlow.metricContractedDeTurckVectorField_eq_sum_inverseGram_correction
#print axioms RicciFlow.contMDiff_metricContractedDeTurckVectorField_of_joint_correction
#print axioms RicciFlow.contMDiff_metricContractedDeTurckGaugeField_of_joint_correction
#print axioms RicciFlow.exists_pos_metricContractedDiffeomorph3GaugeFlowOn_of_joint_correction
#print axioms RicciFlow.contMDiff_metricContractedDeTurckVectorField_of_joint_correctionFunctional
