import PoincareCurvature.Geometry.Manifold.RicciFlow.ChosenLeviCivitaCoordinateCurvature

#print axioms PoincareCurvature.CoordinateMatrixJet.christoffel_lower_symm
#print axioms PoincareCurvature.CoordinateMatrixJet.christoffel_lower_eventuallyEq
#print axioms PoincareCurvature.CoordinateMatrixJet.christoffelFirst_lower_symm
#print axioms PoincareCurvature.CoordinateMatrixJet.coordinateRicci_eq_christoffel_curvature_trace
#print axioms RicciFlow.contMDiffOn_chosenLCCoordinateFrameDerivative
#print axioms RicciFlow.contMDiffOn_chosenLCCoordinateFrameDerivativeCoeff
#print axioms RicciFlow.contDiffOn_scalarReadout_chosenLCCoordinateFrameDerivativeCoeff
#print axioms RicciFlow.chosenLC_coordinateFrameCoeff_mvfderiv_eq_christoffelFirst
#print axioms RicciFlow.chosenLC_coordinateFrameCoeff_curvatureTensor_eq
#print axioms RicciFlow.coordinateRicci_chosenLCMetricCoordinates_eq_intrinsicRicciTensor_transpose
#print axioms RicciFlow.coordinateRicci_chosenLCMetricCoordinates_eq_intrinsicRicciTensor
