import PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.BoundarylessTensorHeatFixedBackground

set_option pp.universes false
set_option format.width 180

#print axioms CovariantDerivative.ManifoldBoundaryless.contDiffOn_writtenInExtChartAt_of_contMDiffOn
#print axioms CovariantDerivative.ManifoldBoundaryless.contDiffOn_localFrameInChart
#print axioms CovariantDerivative.ManifoldBoundaryless.contDiffOn_localFrameInverseGramMatrixInChart
#print axioms CovariantDerivative.ManifoldBoundaryless.contDiffOn_fderivWithin_range
#print axioms CovariantDerivative.ManifoldBoundaryless.contMDiffOn_localTwoTensorConnectionCoefficient
#print axioms CovariantDerivative.ManifoldBoundaryless.contMDiffOn_localThreeTensorConnectionCoefficient
#print axioms CovariantDerivative.ManifoldBoundaryless.contDiffOn_localTwoTensorConnectionCoefficientInChart
#print axioms CovariantDerivative.ManifoldBoundaryless.contDiffOn_localThreeTensorConnectionCoefficientInChart
#print axioms RicciFlow.AnalyticPDE.ManifoldBoundaryless.contDiffOn_actualTensorHeatCoefficients
#print axioms RicciFlow.AnalyticPDE.ManifoldBoundaryless.exists_radius_actualLocalTensorHeatUnitBall_zeroTrace
#print axioms RicciFlow.AnalyticPDE.ManifoldBoundaryless.exists_fixedBackground_actualLocalTensorHeat

#eval IO.println "MANIFOLD_HEAT_TYPES_BEGIN"
#check @CovariantDerivative.ManifoldBoundaryless.contDiffOn_localFrameInChart
#check @RicciFlow.AnalyticPDE.ManifoldBoundaryless.contDiffOn_actualTensorHeatCoefficients
#check @RicciFlow.AnalyticPDE.ManifoldBoundaryless.exists_radius_actualLocalTensorHeatUnitBall_zeroTrace
#check @RicciFlow.AnalyticPDE.ManifoldBoundaryless.exists_fixedBackground_actualLocalTensorHeat
#eval IO.println "MANIFOLD_HEAT_TYPES_END"
