name = "PoincareCurvature"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PoincareCurvature"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8a178386ffc0f5fef0b77738bb5449d50efeea95"

[[lean_lib]]
name = "PoincareCurvature"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
