import LichnerowiczObata.BochnerBound
import LichnerowiczObata.EnergySpectrum
import LichnerowiczObata.ClassicalSpectrum
import LichnerowiczObata.ObataEnergy
import LichnerowiczObata.ObataExtrema
import LichnerowiczObata.ObataRadial
import LichnerowiczObata.EikonalConnection
import LichnerowiczObata.RadialCurves
import LichnerowiczObata.GlobalGradientCurves
import LichnerowiczObata.RegularGradientCurves
import LichnerowiczObata.RadialParameterization
import LichnerowiczObata.RadialVelocity
import LichnerowiczObata.UnitCurveDistance
import LichnerowiczObata.RadialEndpoints
import LichnerowiczObata.RadialEndpointDistance
import LichnerowiczObata.ObataCriticalIsolation

#print axioms LichnerowiczObata.eigenvalue_lower_bound
#print axioms LichnerowiczObata.hessian_equation_of_extremal_eigenfunction
#print axioms LichnerowiczObata.compact_energy_realization
#print axioms LichnerowiczObata.exists_first_variational_eigenpair
#print axioms LichnerowiczObata.exists_weak_laplacian_eigenfunction
#print axioms LichnerowiczObata.Reaction.exists_reaction_jets_on_nested_compacts
#print axioms LichnerowiczObata.exists_smooth_variational_eigenfunction
#print axioms LichnerowiczObata.exists_first_smooth_eigenvalue_with_ricci_bound
#print axioms LichnerowiczObata.differential_gradient_norm_sq
#print axioms LichnerowiczObata.obataEnergy_constant
#print axioms LichnerowiczObata.gradient_eq_zero_of_local_extremum
#print axioms LichnerowiczObata.obata_extrema
#print axioms LichnerowiczObata.obata_critical_values
#print axioms LichnerowiczObata.gradient_comp_hasDerivAt
#print axioms LichnerowiczObata.norm_gradient_obataRadial
#print axioms LichnerowiczObata.exists_obata_radial_eikonal
#print axioms LichnerowiczObata.cov_gradient_self_eq_zero
#print axioms LichnerowiczObata.exists_obata_radial_autoparallel
#print axioms LichnerowiczObata.hasDerivAt_comp_integralCurve
#print axioms LichnerowiczObata.exists_obata_radial_local_curves
#print axioms LichnerowiczObata.exists_uniform_chart_ode
#print axioms LichnerowiczObata.exists_global_integralCurve_compact
#print axioms LichnerowiczObata.exists_global_obata_gradient_curves
#print axioms LichnerowiczObata.tendsto_obata_scalar_atTop
#print axioms LichnerowiczObata.tendsto_obata_scalar_atBot
#print axioms LichnerowiczObata.exists_global_obata_scalar_limits
#print axioms LichnerowiczObata.gradient_ne_zero_along_curve
#print axioms LichnerowiczObata.exists_obata_unique_level_curves
#print axioms LichnerowiczObata.obataClock_along_solution
#print axioms LichnerowiczObata.obataClock_inverse_level
#print axioms LichnerowiczObata.exists_full_obata_radial_parameterization
#print axioms LichnerowiczObata.hasMFDerivAt_integralCurve_timeChange
#print axioms LichnerowiczObata.exists_full_unit_radial_curves
#print axioms LichnerowiczObata.exists_uniform_manifold_ode_contMDiff
#print axioms LichnerowiczObata.contMDiffAt_integralCurve
#print axioms LichnerowiczObata.riemannianEDist_le_of_unit_velocity
#print axioms LichnerowiczObata.riemannianEDist_le_integralCurve
#print axioms LichnerowiczObata.riemannianEDist_le_obataRadial_curve
#print axioms LichnerowiczObata.exists_tendsto_of_riemannianEDist_le
#print axioms LichnerowiczObata.exists_obataRadial_curve_endpoints
#print axioms LichnerowiczObata.obataRadial_endpoint_values
#print axioms LichnerowiczObata.exists_obata_radial_curves_with_endpoints
#print axioms LichnerowiczObata.riemannianEDist_obataRadial_curve_le_abs
#print axioms LichnerowiczObata.riemannianEDist_le_of_curve_tendsto
#print axioms LichnerowiczObata.obataRadial_endpoint_distance
#print axioms LichnerowiczObata.exists_obata_extrema_distance_bounds
#print axioms LichnerowiczObata.fderiv_obataGradientCoordinates
#print axioms LichnerowiczObata.contDiffAt_obataGradientCoordinates
#print axioms LichnerowiczObata.obata_critical_isolated
#print axioms LichnerowiczObata.isDiscrete_obata_critical_set
#print axioms LichnerowiczObata.finite_obata_critical_set
