import LichnerowiczObata.RadialVariation
import LichnerowiczObata.RadialProduct
import LichnerowiczObata.ObataRegularSphere
import LichnerowiczObata.NormalMetricChart
import LichnerowiczObata.IntrinsicNormalMetric
import LichnerowiczObata.NormalAngularTangency
import LichnerowiczObata.GlobalNormalAngularMetric
import LichnerowiczObata.NormalRadialProduct
import LichnerowiczObata.IntrinsicChartLift
import LichnerowiczObata.ObataSphericalMetricProduct
import LichnerowiczObata.IntrinsicAngularCoordinates
import LichnerowiczObata.PolarMetricAssembly
import LichnerowiczObata.FlowVariationEquation
import LichnerowiczObata.CoordinateMetricVariation
import LichnerowiczObata.MetricPairingCalculus
import LichnerowiczObata.MetricBilinearRegularity
import LichnerowiczObata.CoordinateRadialShape
import LichnerowiczObata.ManifoldFlowCoordinates
import LichnerowiczObata.CoordinateAngularVariation
import LichnerowiczObata.ConstructedRadialMetric
import LichnerowiczObata.IntrinsicFlowMetric
import LichnerowiczObata.RadialMetricNormalization
import LichnerowiczObata.SmoothConnectionCoordinates
import LichnerowiczObata.GeodesicLinearization
import LichnerowiczObata.GeodesicEnergy
import LichnerowiczObata.GeodesicHessian
import LichnerowiczObata.GeodesicRadial
import LichnerowiczObata.GeodesicScaling
import LichnerowiczObata.GeodesicNormalRadial
import LichnerowiczObata.GeodesicGauss
import LichnerowiczObata.NormalMetricLimit
import LichnerowiczObata.ScaledRadialMetric
import LichnerowiczObata.NormalRays
import LichnerowiczObata.GeodesicNormalRays
import LichnerowiczObata.NormalRayMetric
import LichnerowiczObata.SineMetricLimit
import LichnerowiczObata.NormalRayNormalization
import LichnerowiczObata.RoundPolarCurves
import LichnerowiczObata.RoundPolarMetric
import LichnerowiczObata.RoundPolarCoordinates
import LichnerowiczObata.RoundPolarInverse
import LichnerowiczObata.RoundPolarHomeomorph
import LichnerowiczObata.SmallRadialLevels
import LichnerowiczObata.NormalLevelHomeomorph
import LichnerowiczObata.IntrinsicNormalChart

import LichnerowiczObata.BochnerBound
import LichnerowiczObata.EnergySpectrum
import LichnerowiczObata.ClassicalSpectrum
import LichnerowiczObata.ObataEnergy
import LichnerowiczObata.ObataExtrema
import LichnerowiczObata.ObataRadial
import LichnerowiczObata.EikonalConnection
import LichnerowiczObata.RadialCurves
import LichnerowiczObata.GlobalGradientCurves
import LichnerowiczObata.RegularGradientCurves
import LichnerowiczObata.RadialParameterization
import LichnerowiczObata.RadialVelocity
import LichnerowiczObata.UnitCurveDistance
import LichnerowiczObata.RadialEndpoints
import LichnerowiczObata.RadialEndpointDistance
import LichnerowiczObata.ObataCriticalIsolation
import LichnerowiczObata.RadialFlowFamily
import LichnerowiczObata.ContinuousPoleMaps
import LichnerowiczObata.ObataUniquePoles
import LichnerowiczObata.RadialDistance
import LichnerowiczObata.AngularMetricEvolution
import LichnerowiczObata.SmoothPicardOperator

#print axioms LichnerowiczObata.contDiffOn_bilinear_of_basis
#print axioms LichnerowiczObata.bilinear_diagonal_basis_expansion
#print axioms LichnerowiczObata.hasFDerivAt_coordinateGeodesicSpray_zero
#print axioms LichnerowiczObata.fderiv_coordinateGeodesicSpray_zero_apply
#print axioms LichnerowiczObata.coordinate_geodesic_at_rest_eventually
#print axioms LichnerowiczObata.hasDerivAt_geodesic_flow_variation_at_rest
#print axioms LichnerowiczObata.flat_variation_eq_affine
#print axioms LichnerowiczObata.fderiv_flow_initial_apply
#print axioms LichnerowiczObata.fderiv_geodesic_flow_at_rest_apply
#print axioms LichnerowiczObata.hasFDerivAt_position_endpoint
#print axioms LichnerowiczObata.hasFDerivAt_geodesic_endpoint_zero
#print axioms LichnerowiczObata.exists_geodesic_endpoint_local_inverse
#print axioms LichnerowiczObata.exists_stationary_coordinate_geodesic_flow
#print axioms LichnerowiczObata.exists_coordinate_geodesic_normal_map
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_energy
#print axioms LichnerowiczObata.coordinate_geodesic_energy_eq
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_rescale
#print axioms LichnerowiczObata.ode_eqOn_of_contDiffAt
#print axioms LichnerowiczObata.coordinate_geodesic_rescale_eqOn
#print axioms LichnerowiczObata.coordinate_geodesic_flow_scaling
#print axioms LichnerowiczObata.coordinate_geodesic_flow_scaling_eventually
#print axioms LichnerowiczObata.fderiv_coordinate_geodesic_endpoint_radial
#print axioms LichnerowiczObata.coordinate_normal_endpoint_radial_gradient
#print axioms LichnerowiczObata.coordinate_normal_endpoint_radius_sq_eventually
#print axioms LichnerowiczObata.hasFDerivAt_symmetric_metric_quadratic
#print axioms LichnerowiczObata.coordinate_normal_endpoint_gauss
#print axioms LichnerowiczObata.continuousAt_pullback_metric_pairing
#print axioms LichnerowiczObata.tendsto_pullback_metric_of_scalar_derivative
#print axioms LichnerowiczObata.tendsto_geodesic_endpoint_metric_at_zero
#print axioms LichnerowiczObata.fderiv_variation_equation_rhs
#print axioms LichnerowiczObata.hasDerivAt_flow_variation_rhs
#print axioms LichnerowiczObata.hasDerivAt_scaled_flow_variation
#print axioms LichnerowiczObata.hasDerivAt_metric_pairing_scaling_longitudinal
#print axioms LichnerowiczObata.hasDerivAt_coordinate_scaled_radial_metric
#print axioms LichnerowiczObata.hasDerivAt_scaled_radial_flow_metric
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_field_pairing
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_gradient_pairing
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_obata_pairing
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_value
#print axioms LichnerowiczObata.hasDerivAt_deriv_coordinate_geodesic_obata
#print axioms LichnerowiczObata.scalar_oscillator_eq_cos
#print axioms LichnerowiczObata.coordinate_geodesic_obata_eq_cos
#print axioms LichnerowiczObata.coordinate_geodesic_obataRadial_eq
#print axioms LichnerowiczObata.coordinate_geodesic_obata_regular
#print axioms LichnerowiczObata.hasDerivAt_chart_curve_value
#print axioms LichnerowiczObata.hasDerivAt_coordinate_geodesic_obataRadial
#print axioms LichnerowiczObata.inner_radial_gradient_coordinate_geodesic_velocity
#print axioms LichnerowiczObata.coordinate_geodesic_velocity_eq_radial
#print axioms LichnerowiczObata.contDiffAt_coordinateVectorField_of_order
#print axioms LichnerowiczObata.contDiffOn_coordinateConnection_basis
#print axioms LichnerowiczObata.contDiffOn_coordinateGeodesicSpray
#print axioms LichnerowiczObata.exists_smooth_coordinate_geodesic_flow
#print axioms LichnerowiczObata.radialVariationMetric_initial
#print axioms LichnerowiczObata.radialVariationMetric_eq_sine_ratio
#print axioms LichnerowiczObata.hasDerivAt_intrinsicFlowMetric
#print axioms LichnerowiczObata.intrinsicFlowMetric_sine_squared_normalized_eq
#print axioms LichnerowiczObata.intrinsicFlowMetric_eq_radialVariationMetric
#print axioms LichnerowiczObata.radialVariationMetric_sine_squared_normalized_eq
#print axioms LichnerowiczObata.symmL_fderiv_chart_map
#print axioms LichnerowiczObata.fderiv_family_spatial
#print axioms LichnerowiczObata.symmL_fderiv_chartFlow
#print axioms LichnerowiczObata.coordinate_flow_metric_eq_intrinsic
#print axioms LichnerowiczObata.radialChartMetricEvolution_of_family
#print axioms LichnerowiczObata.exists_smooth_obata_radial_family_metric
#print axioms LichnerowiczObata.coordinate_variation_angular
#print axioms LichnerowiczObata.coordinate_chartFlow_variation_angular
#print axioms LichnerowiczObata.hasDerivAt_manifold_radial_chart_metric
#print axioms LichnerowiczObata.hasDerivAt_chart_integralCurve
#print axioms LichnerowiczObata.isOpen_chartFlowDomain
#print axioms LichnerowiczObata.contDiffOn_chartFlow
#print axioms LichnerowiczObata.contDiffOn_chartFlow_domain
#print axioms LichnerowiczObata.hasDerivAt_chartFlow
#print axioms LichnerowiczObata.fderiv_coordinateVectorField_add_connection
#print axioms LichnerowiczObata.coordinate_obataRadial_shape
#print axioms LichnerowiczObata.differentiableAt_coordinateVectorField
#print axioms LichnerowiczObata.hasDerivAt_radial_flow_metric
#print axioms LichnerowiczObata.hasDerivAt_coordinate_radial_metric
#print axioms LichnerowiczObata.fderiv_coordinateMetricBilinear_apply
#print axioms LichnerowiczObata.fderiv_coordinateMetricBilinear_coefficients
#print axioms LichnerowiczObata.hasDerivAt_coordinateMetric_pairing_connection
#print axioms LichnerowiczObata.contDiffOn_coordinateMetricBilinear
#print axioms LichnerowiczObata.differentiableAt_coordinateMetricBilinear
#print axioms LichnerowiczObata.eigenvalue_lower_bound
#print axioms LichnerowiczObata.hessian_equation_of_extremal_eigenfunction
#print axioms LichnerowiczObata.compact_energy_realization
#print axioms LichnerowiczObata.exists_first_variational_eigenpair
#print axioms LichnerowiczObata.exists_weak_laplacian_eigenfunction
#print axioms LichnerowiczObata.Reaction.exists_reaction_jets_on_nested_compacts
#print axioms LichnerowiczObata.exists_smooth_variational_eigenfunction
#print axioms LichnerowiczObata.exists_first_smooth_eigenvalue_with_ricci_bound
#print axioms LichnerowiczObata.differential_gradient_norm_sq
#print axioms LichnerowiczObata.obataEnergy_constant
#print axioms LichnerowiczObata.gradient_eq_zero_of_local_extremum
#print axioms LichnerowiczObata.obata_extrema
#print axioms LichnerowiczObata.obata_critical_values
#print axioms LichnerowiczObata.gradient_comp_hasDerivAt
#print axioms LichnerowiczObata.norm_gradient_obataRadial
#print axioms LichnerowiczObata.exists_obata_radial_eikonal
#print axioms LichnerowiczObata.cov_gradient_self_eq_zero
#print axioms LichnerowiczObata.exists_obata_radial_autoparallel
#print axioms LichnerowiczObata.hasDerivAt_comp_integralCurve
#print axioms LichnerowiczObata.exists_obata_radial_local_curves
#print axioms LichnerowiczObata.exists_uniform_chart_ode
#print axioms LichnerowiczObata.exists_global_integralCurve_compact
#print axioms LichnerowiczObata.exists_global_obata_gradient_curves
#print axioms LichnerowiczObata.tendsto_obata_scalar_atTop
#print axioms LichnerowiczObata.tendsto_obata_scalar_atBot
#print axioms LichnerowiczObata.exists_global_obata_scalar_limits
#print axioms LichnerowiczObata.gradient_ne_zero_along_curve
#print axioms LichnerowiczObata.exists_obata_unique_level_curves
#print axioms LichnerowiczObata.obataClock_along_solution
#print axioms LichnerowiczObata.obataClock_inverse_level
#print axioms LichnerowiczObata.exists_full_obata_radial_parameterization
#print axioms LichnerowiczObata.hasMFDerivAt_integralCurve_timeChange
#print axioms LichnerowiczObata.exists_full_unit_radial_curves
#print axioms LichnerowiczObata.exists_uniform_manifold_ode_contMDiff
#print axioms LichnerowiczObata.contMDiffAt_integralCurve
#print axioms LichnerowiczObata.riemannianEDist_le_of_unit_velocity
#print axioms LichnerowiczObata.riemannianEDist_le_integralCurve
#print axioms LichnerowiczObata.riemannianEDist_le_obataRadial_curve
#print axioms LichnerowiczObata.exists_tendsto_of_riemannianEDist_le
#print axioms LichnerowiczObata.exists_obataRadial_curve_endpoints
#print axioms LichnerowiczObata.obataRadial_endpoint_values
#print axioms LichnerowiczObata.exists_obata_radial_curves_with_endpoints
#print axioms LichnerowiczObata.riemannianEDist_obataRadial_curve_le_abs
#print axioms LichnerowiczObata.riemannianEDist_le_of_curve_tendsto
#print axioms LichnerowiczObata.obataRadial_endpoint_distance
#print axioms LichnerowiczObata.exists_obata_extrema_distance_bounds
#print axioms LichnerowiczObata.fderiv_obataGradientCoordinates
#print axioms LichnerowiczObata.contDiffAt_obataGradientCoordinates
#print axioms LichnerowiczObata.obata_critical_isolated
#print axioms LichnerowiczObata.isDiscrete_obata_critical_set
#print axioms LichnerowiczObata.finite_obata_critical_set
#print axioms LichnerowiczObata.exists_uniform_chart_flow
#print axioms LichnerowiczObata.exists_uniform_manifold_flow_contMDiff
#print axioms LichnerowiczObata.exists_continuousOn_integralCurve_family
#print axioms LichnerowiczObata.continuousAt_integralCurve_family_zero
#print axioms LichnerowiczObata.exists_uniform_continuity_interval_integralCurve_family
#print axioms LichnerowiczObata.integralCurve_family_add
#print axioms LichnerowiczObata.continuous_integralCurve_family_time
#print axioms LichnerowiczObata.continuous_integralCurve_family
#print axioms LichnerowiczObata.exists_continuous_global_manifold_flow
#print axioms LichnerowiczObata.continuousOn_obataRadialFamily
#print axioms LichnerowiczObata.exists_continuous_global_gradient_flow
#print axioms LichnerowiczObata.exists_continuous_obata_radial_family
#print axioms LichnerowiczObata.continuousOn_of_uniform_edist_bound
#print axioms LichnerowiczObata.continuousOn_radial_endpoint_maps
#print axioms LichnerowiczObata.exists_continuous_obata_pole_maps
#print axioms LichnerowiczObata.isPreconnected_of_dense_local_traces
#print axioms LichnerowiczObata.exists_openEmbedding_model_neighborhood
#print axioms LichnerowiczObata.finite_compl_local_traces
#print axioms LichnerowiczObata.finite_compl_manifold_preconnected
#print axioms LichnerowiczObata.obata_regular_eq_compl_critical
#print axioms LichnerowiczObata.obata_regular_dense_preconnected
#print axioms LichnerowiczObata.obata_unique_poles
#print axioms LichnerowiczObata.edist_le_riemannianEDist_of_differential_bound
#print axioms LichnerowiczObata.edist_le_riemannianEDist_of_gradient_bound
#print axioms LichnerowiczObata.norm_gradient_obataRadial_le_one
#print axioms LichnerowiczObata.edist_regularized_obataRadial_le
#print axioms LichnerowiczObata.edist_obataRadial_le
#print axioms LichnerowiczObata.obataRadial_le_pole_distance
#print axioms LichnerowiczObata.riemannianEDist_obataRadial_curve_eq_abs
#print axioms LichnerowiczObata.exists_obata_pole_distance
#print axioms LichnerowiczObata.cov_gradient_scalar_comp
#print axioms LichnerowiczObata.obataRadial_hessian_scaled
#print axioms LichnerowiczObata.obataRadial_hessian
#print axioms LichnerowiczObata.cov_obataRadial_gradient
#print axioms LichnerowiczObata.sine_squared_normalized_eq
#print axioms LichnerowiczObata.obataRadial_angular_metric_derivative
#print axioms LichnerowiczObata.obataRadial_angular_metric_scaling
#print axioms LichnerowiczObata.isInvertible_id_sub_of_norm_lt_one
#print axioms LichnerowiczObata.hasStrictFDerivAt_fixedPoint
#print axioms LichnerowiczObata.contDiffAt_fixedPoint
#print axioms LichnerowiczObata.norm_continuousMapApplyCLM_le
#print axioms LichnerowiczObata.hasStrictFDerivAt_continuousMapSuperposition
#print axioms LichnerowiczObata.contDiff_continuousMapSuperposition
#print axioms LichnerowiczObata.contDiff_infty_continuousMapSuperposition
#print axioms LichnerowiczObata.continuous_unitPathExtend
#print axioms LichnerowiczObata.norm_unitPathPrimitive_le
#print axioms LichnerowiczObata.norm_unitPathPrimitiveCLM_le
#print axioms LichnerowiczObata.contDiff_picardPathOperator
#print axioms LichnerowiczObata.contDiffAt_picard_solution_zero
#print axioms LichnerowiczObata.scaledFlowPath_picard
#print axioms LichnerowiczObata.contDiffAt_scaledFlowPath_zero
#print axioms LichnerowiczObata.contDiffAt_flow_zero
#print axioms LichnerowiczObata.exists_contDiff_extension
#print axioms LichnerowiczObata.exists_smooth_local_flow
#print axioms LichnerowiczObata.exists_smooth_local_manifold_flow
#print axioms LichnerowiczObata.contMDiff_integralCurve_family
#print axioms LichnerowiczObata.contMDiff_infty_integralCurve_family
#print axioms LichnerowiczObata.exists_smooth_global_manifold_flow
#print axioms LichnerowiczObata.contDiffAt_obataClock
#print axioms LichnerowiczObata.contMDiffOn_obataRadialFamily
#print axioms LichnerowiczObata.exists_smooth_global_gradient_flow
#print axioms LichnerowiczObata.obataRadialFamily_reset
#print axioms LichnerowiczObata.exists_smooth_obata_radial_family
#print axioms LichnerowiczObata.radialProductEquiv
#print axioms LichnerowiczObata.radialProductHomeomorph
#print axioms LichnerowiczObata.exists_obata_radial_product
#print axioms LichnerowiczObata.inner_gradient_mfderiv_eq_zero
#print axioms LichnerowiczObata.radial_variation_orthogonal
#print axioms LichnerowiczObata.obata_radial_variation_orthogonal
#print axioms LichnerowiczObata.mfderiv_radial_reset
#print axioms LichnerowiczObata.radial_initial_derivative
#print axioms LichnerowiczObata.radial_initial_derivative_of_tangent
#print axioms LichnerowiczObata.radial_transport_kernel_trivial
#print axioms LichnerowiczObata.fderiv_variation_equation
#print axioms LichnerowiczObata.hasDerivAt_flow_variation
#print axioms LichnerowiczObata.contMDiffAt_coordinateConstant
#print axioms LichnerowiczObata.fderiv_coordinateMetric_pairing
#print axioms LichnerowiczObata.covariantDerivative_coordinateConstant
#print axioms LichnerowiczObata.fderiv_coordinateMetric_pairing_coefficients
#print axioms LichnerowiczObata.coordinateMetricBilinear_apply
#print axioms LichnerowiczObata.hasDerivAt_moving_metric_pairing
#print axioms LichnerowiczObata.hasDerivAt_metric_pairing_connection
#print axioms LichnerowiczObata.hasDerivAt_metric_pairing_scaling
#print axioms LichnerowiczObata.hasDerivAt_normal_ray
#print axioms LichnerowiczObata.fderiv_normal_ray_spatial
#print axioms LichnerowiczObata.normal_ray_spatial_metric
#print axioms LichnerowiczObata.hasDerivAt_normal_ray_of_radial
#print axioms LichnerowiczObata.hasDerivAt_geodesic_normal_ray
#print axioms LichnerowiczObata.geodesic_normal_ray_spatial_orthogonal
#print axioms LichnerowiczObata.hasDerivAt_geodesic_normal_ray_metric
#print axioms LichnerowiczObata.sine_squared_normalized_eq_on
#print axioms LichnerowiczObata.geodesic_normal_ray_metric_sine_squared_normalized_eq
#print axioms LichnerowiczObata.tendsto_sine_normalized_quadratic
#print axioms LichnerowiczObata.sine_normalized_eq_of_pole_limit
#print axioms LichnerowiczObata.geodesic_normal_ray_metric_pole_normalized
#print axioms LichnerowiczObata.exists_positive_phase_ray_interval
#print axioms LichnerowiczObata.exists_geodesic_normal_ray_metric_pole_normalized
#print axioms LichnerowiczObata.radial_projection_remainder_orthogonal
#print axioms LichnerowiczObata.bilinear_metric_of_radial_and_angular
#print axioms LichnerowiczObata.geodesic_normal_ray_full_metric
#print axioms LichnerowiczObata.exists_uniform_positive_phase_ray_ball
#print axioms LichnerowiczObata.exists_geodesic_normal_full_metric_ball
#print axioms LichnerowiczObata.norm_orthonormal_pair
#print axioms LichnerowiczObata.roundPolarCurve_mem_sphere
#print axioms LichnerowiczObata.hasDerivAt_roundPolarCurve
#print axioms LichnerowiczObata.roundPolarCurve_velocity_norm
#print axioms LichnerowiczObata.roundPolarCurve_zero
#print axioms LichnerowiczObata.roundPolarCurve_antipode
#print axioms LichnerowiczObata.hasFDerivAt_roundPolarCurve_angular
#print axioms LichnerowiczObata.roundPolarCurve_angular_metric
#print axioms LichnerowiczObata.roundPolarCurve_mixed_metric
#print axioms LichnerowiczObata.roundPolarCurve_angular_tangent
#print axioms LichnerowiczObata.roundPolarCurve_full_metric
#print axioms LichnerowiczObata.roundPolarCurve_height
#print axioms LichnerowiczObata.roundPolarCurve_coordinates_unique
#print axioms LichnerowiczObata.roundPolarMap_injective
#print axioms LichnerowiczObata.continuous_roundPolarMap
#print axioms LichnerowiczObata.unit_sphere_height_strict
#print axioms LichnerowiczObata.unit_sphere_polar_decomposition
#print axioms LichnerowiczObata.roundPolarMap_surjective_off_poles
#print axioms LichnerowiczObata.roundPolarCurve_ne_poles
#print axioms LichnerowiczObata.roundPolarPuncturedMap_bijective
#print axioms LichnerowiczObata.roundPolarEquiv
#print axioms LichnerowiczObata.continuous_roundPolarPuncturedMap
#print axioms LichnerowiczObata.roundPolarEquiv_inverse_radius
#print axioms LichnerowiczObata.roundPolarEquiv_inverse_angular
#print axioms LichnerowiczObata.roundPolar_inverse_sine_ne_zero
#print axioms LichnerowiczObata.continuous_roundPolarEquiv_inverse
#print axioms LichnerowiczObata.roundPolarHomeomorph
#print axioms LichnerowiczObata.exists_small_sublevel_subset_of_unique_zero
#print axioms LichnerowiczObata.exists_small_obata_radial_sublevel_subset
#print axioms LichnerowiczObata.chartLevelHomeomorph
#print axioms LichnerowiczObata.normalSphereLevelHomeomorph
#print axioms LichnerowiczObata.exists_small_sphere_level_homeomorph
#print axioms LichnerowiczObata.coordinate_normal_endpoint_radius_at_zero_eventually
#print axioms LichnerowiczObata.intrinsic_normal_endpoint_radius_at_zero_eventually
#print axioms LichnerowiczObata.exists_intrinsic_radial_normal_chart
#print axioms LichnerowiczObata.exists_obata_radial_normal_chart
#print axioms LichnerowiczObata.exists_small_obata_sphere_levels
#print axioms LichnerowiczObata.wholeLevelHomeomorph
#print axioms LichnerowiczObata.exists_obata_whole_level_product
#print axioms LichnerowiczObata.exists_obata_radial_product_with_energy
#print axioms LichnerowiczObata.obata_whole_level_product_at_positive_critical_value
#print axioms LichnerowiczObata.exists_obata_tangent_sphere_product
#print axioms LichnerowiczObata.obata_regular_tangent_sphere_product
#print axioms LichnerowiczObata.obata_punctured_tangent_sphere_product
#print axioms LichnerowiczObata.exists_obata_normal_metric_chart
#print axioms LichnerowiczObata.coordinate_metric_eq_intrinsic_chart_lift
#print axioms LichnerowiczObata.exists_obata_intrinsic_angular_chart
#print axioms LichnerowiczObata.fderiv_eq_zero_of_scaled_norm_identity
#print axioms LichnerowiczObata.mfderiv_normal_angular_eq_zero
#print axioms LichnerowiczObata.normal_angular_metric_transport
#print axioms LichnerowiczObata.normal_angular_composite_metric
#print axioms LichnerowiczObata.exists_normal_chart_global_angular_metric
#print axioms LichnerowiczObata.exists_obata_global_angular_metric
#print axioms LichnerowiczObata.exists_small_sphere_level_homeomorph_map
#print axioms LichnerowiczObata.exists_normal_radial_product_map
#print axioms LichnerowiczObata.exists_intrinsic_chart_lift
#print axioms LichnerowiczObata.exists_coordinate_normal_radial_product_map
#print axioms LichnerowiczObata.exists_obata_spherical_metric_product
#print axioms LichnerowiczObata.coordinate_metric_trivialization_forward
#print axioms LichnerowiczObata.angular_metric_precompose_linear
#print axioms LichnerowiczObata.angular_metric_rescale_unit
#print axioms LichnerowiczObata.mdifferentiableAt_normal_radial_composite
#print axioms LichnerowiczObata.normal_radial_composite_intrinsic_angular_metric
#print axioms LichnerowiczObata.polar_derivative_split
#print axioms LichnerowiczObata.polar_derivative_full_pairing
#print axioms LichnerowiczObata.polar_map_spatial_orthogonal
#print axioms LichnerowiczObata.polar_map_full_pairing
#print axioms LichnerowiczObata.mdifferentiableAt_normal_radial_joint
#print axioms LichnerowiczObata.normal_radial_joint_level_eventually
