name = "LichnerowiczObata"
version = "0.1.0"
defaultTargets = ["LichnerowiczObata", "LichnerowiczObataChallenge", "LichnerowiczObataSolution"]

[[require]]
name = "AlmostSchur"
path = "../almost-schur"

[[lean_lib]]
name = "LichnerowiczObata"
globs = ["LichnerowiczObata.+"]

[[lean_lib]]
name = "LichnerowiczObataChallenge"
roots = ["LichnerowiczObataChallenge"]

[[lean_lib]]
name = "LichnerowiczObataSolution"
roots = ["LichnerowiczObataSolution"]
