name: Documentation

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  local-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Check local documentation links
        run: python3 scripts/check-doc-links.py
