import AlmostSchur

#print axioms AlmostSchur.gradient
#print axioms AlmostSchur.inner_gradient
#print axioms AlmostSchur.gradient_eq_of_inner
#print axioms AlmostSchur.gradient_eq_zero_iff
#print axioms AlmostSchur.norm_gradient
#print axioms AlmostSchur.differential_gradient
#print axioms AlmostSchur.hessian
#print axioms AlmostSchur.hessian_apply
#print axioms AlmostSchur.laplacian
#print axioms AlmostSchur.laplacian_eq_sum_hessian
#print axioms AlmostSchur.sum_hessian_basis_independent
#print axioms AlmostSchur.hilbertSchmidtSq
#print axioms AlmostSchur.hilbertSchmidtSq_eq_sum_norm_sq
#print axioms AlmostSchur.hilbertSchmidtSq_eq_sum_sq
#print axioms AlmostSchur.hilbertSchmidtSq_nonneg
#print axioms AlmostSchur.traceFree
#print axioms AlmostSchur.trace_traceFree
#print axioms AlmostSchur.hilbertSchmidtSq_sub_smul_id
#print axioms AlmostSchur.hilbertSchmidtSq_traceFree
#print axioms AlmostSchur.hessianNormSq
#print axioms AlmostSchur.traceFreeHessianNormSq
#print axioms AlmostSchur.hessianNormSq_eq_sum_sq
#print axioms AlmostSchur.traceFreeHessianNormSq_eq
#print axioms AlmostSchur.volumeMeasure
#print axioms AlmostSchur.volumeMeasure_pos_of_mem_nhds
#print axioms AlmostSchur.volumeMeasure_univ_pos
#print axioms AlmostSchur.volumeMeasure_finite
#print axioms AlmostSchur.totalVolume_pos
